stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update -qq && apt-get install -qqy python3 python3-pip
  - pip3 install -r requirements.txt

build:
  stage: build
  script:
    - docker build -t myproject .

test:
  stage: test
  script:
    - docker-compose run web python manage.py test

deploy:
  stage: deploy
  script:
    - docker-compose up -d
